version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: byeoryback
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: byeoryback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: byeoryback
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data