version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: byeoryback
    command:
      - --sort-buffer-size=4M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: byeoryback
      MYSQL_ROOT_PASSWORD: byeoryback
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql